export const azureArmRegions = [
  { name: "Australia Central", armRegionName: "australiacentral" },
  { name: "Australia Central 2", armRegionName: "australiacentral2" },
  { name: "Australia East", armRegionName: "australiaeast" },
  { name: "Australia Southeast", armRegionName: "australiasoutheast" },
  { name: "Austria East", armRegionName: "austriaeast" },
  { name: "Belgium Central", armRegionName: "belgiumcentral" },
  { name: "Brazil South", armRegionName: "brazilsouth" },
  { name: "Brazil Southeast", armRegionName: "brazilsoutheast" },
  { name: "Canada Central", armRegionName: "canadacentral" },
  { name: "Canada East", armRegionName: "canadaeast" },
  { name: "Central India", armRegionName: "centralindia" },
  { name: "Central US", armRegionName: "centralus" },
  { name: "Central US EUAP", armRegionName: "centraluseuap" },
  { name: "Chile Central", armRegionName: "chilecentral" },
  { name: "Denmark East", armRegionName: "denmarkeast" },
  { name: "East Asia", armRegionName: "eastasia" },
  { name: "East US", armRegionName: "eastus" },
  { name: "East US 2", armRegionName: "eastus2" },
  { name: "East US 2 EUAP", armRegionName: "eastus2euap" },
  { name: "France Central", armRegionName: "francecentral" },
  { name: "France South", armRegionName: "francesouth" },
  { name: "Germany North", armRegionName: "germanynorth" },
  { name: "Germany West Central", armRegionName: "germanywestcentral" },
  { name: "Indonesia Central", armRegionName: "indonesiacentral" },
  { name: "Israel Central", armRegionName: "israelcentral" },
  { name: "Italy North", armRegionName: "italynorth" },
  { name: "Japan East", armRegionName: "japaneast" },
  { name: "Japan West", armRegionName: "japanwest" },
  { name: "Jio India Central", armRegionName: "jioindiacentral" },
  { name: "Jio India West", armRegionName: "jioindiawest" },
  { name: "Korea Central", armRegionName: "koreacentral" },
  { name: "Korea South", armRegionName: "koreasouth" },
  { name: "Malaysia South", armRegionName: "malaysiasouth" },
  { name: "Malaysia West", armRegionName: "malaysiawest" },
  { name: "Mexico Central", armRegionName: "mexicocentral" },
  { name: "New Zealand North", armRegionName: "newzealandnorth" },
  { name: "North Central US", armRegionName: "northcentralus" },
  { name: "North Europe", armRegionName: "northeurope" },
  { name: "Norway East", armRegionName: "norwayeast" },
  { name: "Norway West", armRegionName: "norwaywest" },
  { name: "Poland Central", armRegionName: "polandcentral" },
  { name: "Qatar Central", armRegionName: "qatarcentral" },
  { name: "South Africa North", armRegionName: "southafricanorth" },
  { name: "South Africa West", armRegionName: "southafricawest" },
  { name: "South Central US", armRegionName: "southcentralus" },
  { name: "South India", armRegionName: "southindia" },
  { name: "Southeast Asia", armRegionName: "southeastasia" },
  { name: "Spain Central", armRegionName: "spaincentral" },
  { name: "Sweden Central", armRegionName: "swedencentral" },
  { name: "Sweden South", armRegionName: "swedensouth" },
  { name: "Switzerland North", armRegionName: "switzerlandnorth" },
  { name: "Switzerland West", armRegionName: "switzerlandwest" },
  { name: "UAE Central", armRegionName: "uaecentral" },
  { name: "UAE North", armRegionName: "uaenorth" },
  { name: "UK South", armRegionName: "uksouth" },
  { name: "UK West", armRegionName: "ukwest" },
  { name: "US Gov Arizona", armRegionName: "usgovarizona" },
  { name: "US Gov Texas", armRegionName: "usgovtexas" },
  { name: "US Gov Virginia", armRegionName: "usgovvirginia" },
  { name: "West Central US", armRegionName: "westcentralus" },
  { name: "West Europe", armRegionName: "westeurope" },
  { name: "West India", armRegionName: "westindia" },
  { name: "West US", armRegionName: "westus" },
  { name: "West US 2", armRegionName: "westus2" },
  { name: "West US 3", armRegionName: "westus3" }
] as const;
